name: Build Debug Apk

on:
  push:
    tags :
       - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name : Build Debug Apk
      run: ./gradlew assembleDebug
    - name: Upload Apk Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./app/build/outputs/apk/dev/debug/app-debug-dev.apk
